from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

import pandas as pd

APP_CODE_DIR = Path(__file__).resolve().parent
APP_HELPER_DIR = APP_CODE_DIR / "src"
if str(APP_HELPER_DIR) not in sys.path:
    sys.path.insert(0, str(APP_HELPER_DIR))

from path_utils import add_project_root_to_path

PROJECT_ROOT = add_project_root_to_path()
APP_ROOT = APP_CODE_DIR.parent


def validate_result(path: Path) -> None:
    df = pd.read_csv(path, dtype={"stock_id": str})
    required = {"stock_id", "weight"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"result.csv missing columns: {sorted(missing)}")
    if df.empty:
        raise ValueError("result.csv is empty")
    if len(df) > 5:
        raise ValueError("result.csv contains more than 5 stocks")
    if not df["stock_id"].astype(str).str.fullmatch(r"\d{6}").all():
        raise ValueError("stock_id must be 6-digit stock codes")
    if float(df["weight"].sum()) > 1.0 + 1e-8:
        raise ValueError("weight sum exceeds 1.0")
    if (df["weight"] < 0).any():
        raise ValueError("negative weights are not allowed")


def main() -> None:
    parser = argparse.ArgumentParser(description="Official app/ inference entrypoint.")
    parser.add_argument(
        "--model-result",
        default=str(APP_ROOT / "model" / "result.csv"),
        help="Submission generated by train.py and stored in the image/model volume.",
    )
    parser.add_argument(
        "--final-output",
        default=str(APP_ROOT / "output" / "result.csv"),
    )
    args = parser.parse_args()

    model_result = Path(args.model_result)
    if not model_result.exists():
        bundled_result = PROJECT_ROOT / "model" / "result.csv"
        app_bundled_result = APP_ROOT / "model" / "result.csv"
        if app_bundled_result.exists():
            model_result = app_bundled_result
        elif bundled_result.exists():
            model_result = bundled_result
        else:
            raise FileNotFoundError("Missing model/result.csv. Run train.sh before test.sh.")
    final_output = Path(args.final_output)
    final_output.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(model_result, final_output)
    validate_result(final_output)
    print(f"test completed: {final_output}")


if __name__ == "__main__":
    main()
